### ISSUE TITLE
Freerouting stuck loading design

### ISSUE THREAD

**Issue by scd31** [miho/freerouting#11] opened 2020-02-18 12:23 UTC
I am having an issue when loading my design into the autorouter. It is a .dsn file which I exported from Kicad.

I can see Freerouting using 100% of one of my CPU cores. I left it for about 30 minutes and observed no changes. The only error I get is "Component.read_place_scope: ) expected"

I can provide my DSN file if needed. I am using Kicad 5.

**Comment by scd31** [comment] 2020-02-19 17:42
I found the issue. My project contains a keyboard, which has keys labelled such as " and `. Both of these caused problems, and once I removed them I was able to open the file in Freerouting.

I'm not sure if this is an issue with Kicad or Freerouting. Regardless, it would be nice if Freerouting gave more specific errors(with line numbers)

**Comment by andrasfuchs** [comment] 2020-02-28 13:15
@scd31 Thank you for your feedback. Sorry for not getting back sooner, I forgot to set the notifications about new issues here on GitHub.

Could you provide the .DSN file that caused the problem? Then I could reproduce it, and at least make an error entry in the log file/on the console.

**Comment by andrasfuchs** [comment] 2020-03-01 15:20
I don't have your dsn file, so I couldn't test it, but I extended the error messages in the DSN loader, so you can at least see at which position the problem is.

I close this issue for now, but if you feel like sharing your .dsn file, I can test it and implement a more sophisticated fix if needed.

**Closed as completed by andrasfuchs** 2020-03-01 15:20 UTC

**Comment by scd31** [comment] 2020-03-01 15:45
Unfortunately I no longer have the dsn file. However, it can be reproduced by naming a part " or ` and exporting the DSN file in Kicad.
